from typing import Any, Dict, List, Optional, Union, BinaryIO

class ClientOptionsFromEnv:
    def __init__(self, options: Optional[Dict[str, Any]] = None) -> None: ...

class PrerecordedOptions:
    def __init__(self, **kwargs: Any) -> None: ...

class DeepgramClient:
    def __init__(self, api_key: Optional[str] = None, config: Optional[ClientOptionsFromEnv] = None) -> None: ...
    @property
    def listen(self) -> "ListenClient": ...

class ListenClient:
    @property
    def prerecorded(self) -> "PrerecordedClient": ...

class PrerecordedClient:
    def v(self, version: str) -> "PrerecordedVersionClient": ...

class PrerecordedVersionClient:
    def transcribe_file(self, source: Dict[str, Any], options: Optional[Any] = None) -> Any: ...
